// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: cart_item.sql

package models

import (
	"context"

	"github.com/google/uuid"
)

const listCartItemsByCartID = `-- name: ListCartItemsByCartID :many
SELECT id, cart_id, item_type, item_name, discount, version, quantity, inventory_id, amount, cgst, igst, sgst FROM cart_item WHERE cart_id = $1
`

func (q *Queries) ListCartItemsByCartID(ctx context.Context, cartID uuid.UUID) ([]CartItem, error) {
	rows, err := q.db.Query(ctx, listCartItemsByCartID, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartItem{}
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ItemType,
			&i.ItemName,
			&i.Discount,
			&i.Version,
			&i.Quantity,
			&i.InventoryID,
			&i.Amount,
			&i.Cgst,
			&i.Igst,
			&i.Sgst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
